apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: xs1yjtuvu-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/xs1yjtuvu-dotnet-basic-gitops